# Generated by Django 3.2.4 on 2021-06-13 21:40

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('city', models.CharField(max_length=32)),
                ('image', models.ImageField(upload_to='media/')),
                ('description', models.TextField(max_length=360)),
                ('difficulty', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('animal', models.CharField(choices=[('Perro', 'PERRO'), ('Gato', 'GATO')], max_length=6)),
                ('age', models.CharField(choices=[('Joven', 'JOVEN'), ('Adulto', 'ADULTO'), ('Mayor', 'MAYOR')], max_length=6)),
                ('gender', models.CharField(choices=[('Macho', 'MACHO'), ('Hembra', 'HEMBRA')], max_length=7)),
                ('sheltered', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
